### ISSUE TITLE
A question about the metrics in the paper 

### ISSUE THREAD

**Issue by loklok-infi** [mit-han-lab/llm-awq#10]
Hello~, I'm reading AWQ and have a small question about the metrics. I found the results about OPT on wikitext-2 in AWQ are different from what it is in GPTQ's paper, 

![image](https://github.com/mit-han-lab/llm-awq/assets/10709532/d190df64-362b-4fc1-ad01-bfe02a734d33)
(results from AWQ)

![image](https://github.com/mit-han-lab/llm-awq/assets/10709532/46ff44c8-8980-4cb1-90c7-e7dea2cd6a44)
(results from GPTQ)

![image](https://github.com/mit-han-lab/llm-awq/assets/10709532/1ac6faac-8545-4b15-8ae4-c616e391ee70)
(results from SqPR, basically same with GPTQ)

would that be a problem? is it due to the different experiment setting or I missed something?

**Comment by Sakits** [comment]
Hi @loklok-infi, 

Thanks for your interests in our work! 
I think there are two potential reasons for the difference in the results:
(i) We used [lm-eval-harness](https://github.com/EleutherAI/lm-evaluation-harness) for evaluation, whereas GPTQ used their own implementation for evaluation (please refer [here](https://github.com/IST-DASLab/gptq/blob/ff75576b05c3bb1df99f43b570528d18f9ff0e6d/opt.py#L208)).
(ii) The results from GPTQ's paper are based on per-channel quantization without using group quantization. Our results are based on group quantization with a group size of 128.
Hope this answers your question :)

**Comment by Sakits** [comment]
Hi @loklok-infi, 

Thanks for your interests in our work! 
I think there are two potential reasons for the difference in the results:
(i) We used [lm-eval-harness](https://github.com/EleutherAI/lm-evaluation-harness) for evaluation, while GPTQ used their own implementation for evaluation (please refer [here](https://github.com/IST-DASLab/gptq/blob/ff75576b05c3bb1df99f43b570528d18f9ff0e6d/opt.py#L208)). There might be some differences in the experiment settings between them.
(ii) Regarding the 3/4-bit results, the results from GPTQ's paper are based on per-channel quantization without using group quantization. Our results are based on group quantization with a group size of 128.
Hope this answers your question :)

**Comment by loklok-infi** [comment]
> Hi @loklok-infi,
> 
> Thanks for your interests in our work! I think there are two potential reasons for the difference in the results: (i) We used [lm-eval-harness](https://github.com/EleutherAI/lm-evaluation-harness) for evaluation, while GPTQ used their own implementation for evaluation (please refer [here](https://github.com/IST-DASLab/gptq/blob/ff75576b05c3bb1df99f43b570528d18f9ff0e6d/opt.py#L208)). There might be some differences in the experiment settings between them. (ii) Regarding the 3/4-bit results, the results from GPTQ's paper are based on per-channel quantization without using group quantization. Our results are based on group quantization with a group size of 128. Hope this answers your question :)

Thank you for answering! Actually what confuses me more is the fp16 results are also ~10% different, but as you said I guess it's from the lm-eval-harness and the implementation of GPTQ.

I guess it's a problem for the whole community today, a similar problem seems happened between huggingface's LLM leaderboard and LLaMA's official result, hope soon we could have a one-true-standard benchmark implementation for LLMs.

**Comment by loklok-infi** [comment]
> here's the performance:
> 
> [LLaMA-7B](https://arxiv.org/abs/2302.13971)	BPW	Wikitext2
> FP16	16	5.68
> RTN	4.00	6.29
> RTN	3.00	25.54
> GPTQ-128g	4.15	5.85
> GPTQ-128g	3.15	6.61
> AWQ-128g	4.15	5.81
> AWQ-128g	3.15	6.46
> AWQ-32g	3.60	6.10
> SpQR-3b-16g-3b-32g-0.4%	3.63	5.73
> AWQ is more hardware efficient and simpler to implement than SpQR, but the compression ratio seems to be worse than SpQR.

Thank you! It's very helpful👍

**Comment by JianbangZ** [comment]
> here's the performance:
> 
> [LLaMA-7B](https://arxiv.org/abs/2302.13971)	BPW	Wikitext2
> FP16	16	5.68
> RTN	4.00	6.29
> RTN	3.00	25.54
> GPTQ-128g	4.15	5.85
> GPTQ-128g	3.15	6.61
> AWQ-128g	4.15	5.81
> AWQ-128g	3.15	6.46
> AWQ-32g	3.60	6.10
> SpQR-3b-16g-3b-32g-0.4%	3.63	5.73
> AWQ is more hardware efficient and simpler to implement than SpQR, but the compression ratio seems to be worse than SpQR.

Hey do you have a repo to benchmark all these quant methods?

**Comment by Sravanth-k27** [comment]
> > here's the performance:
> > [LLaMA-7B](https://arxiv.org/abs/2302.13971)	BPW	Wikitext2
> > FP16	16	5.68
> > RTN	4.00	6.29
> > RTN	3.00	25.54
> > GPTQ-128g	4.15	5.85
> > GPTQ-128g	3.15	6.61
> > AWQ-128g	4.15	5.81
> > AWQ-128g	3.15	6.46
> > AWQ-32g	3.60	6.10
> > SpQR-3b-16g-3b-32g-0.4%	3.63	5.73
> > AWQ is more hardware efficient and simpler to implement than SpQR, but the compression ratio seems to be worse than SpQR.
> 
> Hey do you have a repo to benchmark all these quant methods?

Yes , Code for this benchmark will be appreciated
