### ISSUE TITLE
Help me understand, this is weight only quant?

### ISSUE THREAD

**Issue by JianbangZ** [mit-han-lab/llm-awq#11]
So the activations are kept at FP16, so basically W8A16, W4A16, W3A16?

**Comment by tonylins** [comment]
Yes, currently we support W4A16 and W3A16.

**Comment by brisker** [comment]
@tonylins 
it seems that this papaer is a typical PTQ paper(Post-Training-Quantization), so have you do any experiments or attempts about QAT(quantization-aware-training) or low-precision training(quantize both forward and backward, including gradients) on LLMs?

**Comment by tonylins** [comment]
@brisker AWQ is a PTQ method. We have some research on training-aware quantization, but it is still undergoing :)
