### ISSUE TITLE
Bug report: cuda kernel gemm output nan for last token randomly, while gemv is ok

### ISSUE THREAD

**Issue by yyfcc17** [mit-han-lab/llm-awq#113]
i supported chatglm2-6b in awq, but the **WQLinear** **gemm** kernel output **nan** for the last token, it begin to occur in one **WQLinear** layer in the middle randomly, not in a specific **WQLinear** layer.

can't upload image, but the **output** of this **WQLinear** looks like this, shape (329, 4096):
[right data     ....]
[right data     ....]
....
[nan nan nan ....]

i forced to use **gemv** kernel by commenting out some lines in forward, the result is right then, so i think there is a bug in awq **gemm** implementation, maybe some corner case is not well considered.

    @torch.no_grad()
    def forward(self, x):
        out_shape = x.shape[:-1] + (self.out_features, )
        inputs = x.reshape(-1, x.shape[-1])

        # if inputs.shape[0] > 8:
        #     out = awq_inference_engine.gemm_forward_cuda(inputs, self.qweight, self.scales, self.qzeros, self.group_size, self.split_k_iters)
        # else:
        out = awq_inference_engine.gemv_forward_cuda(inputs, self.qweight, self.scales, self.qzeros, self.group_size)

        out = out + self.bias if self.bias is not None else out

        return out.reshape(out_shape)

i can provide data to reproduce this later.

**Comment by Hongbosherlock** [comment]
> can't upload data in company network, i will close this, AutoAWQ has no bug in my case, chatglm2

I had similar issues, AutoAWQ works for me too.
