### ISSUE TITLE
Quantization of larger models on smaller GPUs using CPU offloading

### ISSUE THREAD

**Issue by abhinavkulkarni** [mit-han-lab/llm-awq#15]
Hi,

I was trying to quantize `facebook/opt-6.7b` on RTX 3060 (12GB of VRAM) and was running into OOM errors. 

I tried supplying my own `device_map` (instead of `device_map="balanced"`), the quantization progressed to 3rd layer and then I was getting this error in `accelerate`:

```
NotImplementedError: Cannot copy out of meta tensor; no data!
```

I think carefully using `accelerate` and CPU offloading, it should be possible to quantize larger models on smaller GPUs.

Can you please look into this? Or provide some guidance as to where to make changes in the code?

Thanks!

**Comment by tonylins** [comment]
Hi,  may I know if you are loading and applying the pre-computed scales, or are you doing the AWQ search yourself?

I think our current implementation does not use techniques like offloading to reduce GPU memory usage during the quantization stage. We can definitely add that to reduce GPU memory usage. What do you think @Sakits ?

**Comment by abhinavkulkarni** [comment]
Hey @tonylins,

I was trying to do AWQ search. Since AWQ works layer by layer, the entire model should be loaded into RAM and only the layer that is being quantized should be moved to GPU. It should be possible to leverage `accelerate` to do so.

**Comment by Sakits** [comment]
Hi @abhinavkulkarni ,
We have added the CPU offloading support for run_awq in the dev/more_models branch. Now you should able to run awq for opt-6.7b on a single RTX 3060-12G. Welcome to try it out and feel free to bring up any issues you might encounter!

Thanks for your interest in our work!

**Comment by abhinavkulkarni** [comment]
Hi @Sakits, @tonylins,

Thanks for adding support for CPU offloading. I had to make additional changes on top of your branch to enable all the steps - run AWQ search for scale and clip values, evaluate using fake quantization, dump AWQ weights and run AWQ evaluation using quantized weights.

You can view the changes in my forked branch here: https://github.com/mit-han-lab/llm-awq/compare/dev/more_models...abhinavkulkarni:dev/more_models?expand=1

If they look okay to you, I'd be happy to raise a PR.

I had to hard the value of `max_memory` according to my GPU (12GB of VRAM), but I'd be happy to add `--max-memory` argument to the command line.

**Comment by Sakits** [comment]
Hi @abhinavkulkarni, 

Thank you for your contributions on enhancing the CPU offloading and `--max-memory` argument!
We'd definitely welcome a pr from you!

**Comment by abhinavkulkarni** [comment]
Thanks @Sakits, I have opened a PR: https://github.com/mit-han-lab/llm-awq/pull/22

I was able to run all the steps for `mosiacml/mpt-7b-instruct` model on RTX 3060 (12GB of VRAM).
