### ISSUE TITLE
Question about scale search and apply

### ISSUE THREAD

**Issue by cghsncg** [mit-han-lab/llm-awq#246]
![1734071140628](https://github.com/user-attachments/assets/350caab2-2637-4a3b-a329-af6d8b68819d)

When searching for "scale," the search order is as follows: qkv proj, o proj, gateup proj, down proj. And when using these scales for 
smoothing, the same order is followed:qkv proj, o proj, gateup proj, down proj.
![1734071666539](https://github.com/user-attachments/assets/80a8d32c-321d-4e40-97c3-13492cb95bba)

My question is ，for example ,like smooth in this order ， (1) (laynorm, v_proj)  (2)(v_proj , o_proj) ，the second step will rwrite 的 weight of v_proj ，it might disable the first step. The same as (1) (laynorm, up_proj)  (2)(up_proj, down_proj) .
![1734073873300](https://github.com/user-attachments/assets/cdaa5e74-3303-45ad-a3f6-bbfcb332a38c)

So i think the correct order is search o_proj,down_proj  scale and aply. And then search qkv, gateup scale, and apply ?
I’m not sure if my idea is correct. If it’s convenient, I’d appreciate it if you could address my question.

**Comment by zhang110112110** [comment]
I have the same question.
