### ISSUE TITLE
3bit backward implementation

### ISSUE THREAD

**Issue by qwopqwop200** [mit-han-lab/llm-awq#3]
Thank you for your amazing work. Do you have any plans to implement 3 bit backward (transpose matmul)?
I think this can apply LoRA to the model in 3 bits. like QLoRA

**Comment by qwopqwop200** [comment]
> Thank you for your amazing work. Do you have any plans to implement 3 bit backward (transpose matmul)?
> I think this can apply LoRA to the model in 3 bits. like QLoRA

**Comment by tonylins** [comment]
Thanks for your interests in our work! For now, we focus on 4-bit implementation since it offers noticeable better accuracy compared to 3-bit, we will see if there is a big need for 3-bit kernels.

**Comment by madhav120ai** [comment]
hi, is there any update on this?
