### ISSUE TITLE
Has XGen models by Salesforce been tested?

### ISSUE THREAD

**Issue by casperbh96** [mit-han-lab/llm-awq#32]
They trained a 7B model with 8k context with largely the same architecture as LLaMa, and I am wondering if it is compatible with AWQ since it may be very similar but just permissively licensed. 

Model: https://huggingface.co/Salesforce/xgen-7b-8k-base

**Comment by tonylins** [comment]
Hi, we have not tested the model. But if it uses the same codebase as LLaMA, it should work as well. Let us know if you meet any problem when trying the model.

**Comment by abhinavkulkarni** [comment]
@casperbh96: I was able to AWQ quantized `Salesforce/codegen25-7b-multi` using this repo ([link](https://huggingface.co/abhinavkulkarni/Salesforce-codegen25-7b-multi-w4-g128-awq)). So, it should be possible to quantized the XGen models as well.

**Comment by tonylins** [comment]
Thanks for verifying! I will mark the issue as closed. Feel free to reopen if you have more questions.
