### ISSUE TITLE
Merge the more models branch with main branch

### ISSUE THREAD

**Issue by casperbh96** [mit-han-lab/llm-awq#35]
Hello maintainers! Just wondering when you are planning to merge the changes that allows for more models into main?

**Comment by abhinavkulkarni** [comment]
Hey @Sakits,

Can you please look at the open PR https://github.com/mit-han-lab/llm-awq/pull/36 and merge it if everything looks good? I have extensively tested it and have even released multiple quantized models on HuggingFace ([link](https://huggingface.co/abhinavkulkarni?sort_models=downloads#models)).

**Comment by Sakits** [comment]
Hi @abhinavkulkarni, 

The quantized models you've shared on HuggingFace are impressive! Thank you for your valuable contribution! 
My bandwidth has been limited in recent times. I will prioritize reviewing and merging your PR as soon as I can.
