### ISSUE TITLE
Which "activations" are assumed in this work?

### ISSUE THREAD

**Issue by Andrey36652** [mit-han-lab/llm-awq#4]
Hello, thanks for your work. 
> We hypothesize that the input features with larger magnitudes are generally more important.

Do you mean "activations" = "input features" = encircled matrices in this picture (from blogpost http://jalammar.github.io/illustrated-transformer/)?
![image](https://github.com/mit-han-lab/llm-awq/assets/35865938/3a232884-44c2-42fc-8e69-270325eca6e7)
And, if so, why did you decide to use input features, but not calculated Q, K, V (and maybe Z as it's referred in the picture) values as measure of saliency of weights?

**Comment by tonylins** [comment]
Hi, activations in the paper refer to input activations. Given some input activations, we think it is natural to protect some features by analyzing the input channels of linear layers. Analyzing the output channel may or may not work, which we have not tried. Let me know if it answers your question.

**Comment by tonylins** [comment]
I will close the issue due to inactivity. Feel free to reopen.
