### ISSUE TITLE
[Question/Feature] Skip initialization after quantization

### ISSUE THREAD

**Issue by casperbh96** [mit-han-lab/llm-awq#44]
Hi maintainers.

I have been developing models using your AWQ library, which has significantly increased the speed. I have noticed there is a challenge when loading the weights again after quantization because we need to run in init_only mode to [load weights correctly and replace layers](https://github.com/mit-han-lab/llm-awq/blob/main/awq/quantize/quantizer.py#L122). This took me roughly 10-12 seconds on a 3090.

Have you thought of a way to 1) quantize weights, 2) save weights with blocks/layers replaced, and 3) load weights without needing to initialize again?

The rationale is that we can get loading times down since we would not need to re-initialize every time we need to load the model.

**Comment by tonylins** [comment]
Hi, thanks for the suggestion. We will work on this shortly.

**Comment by casperbh96** [comment]
Thank you @tonylins and @Sakits. I'm quite certain load times can get down to ~2 seconds, which would be a significant feature since normally it will take 10-20 seconds to load.

**Comment by Sakits** [comment]
Hi @casperbh96,

Thank you for your feedback! 
Please try the latest version of our AWQ library, it should be a lot faster now.

**Comment by casperbh96** [comment]
> Hi @casperbh96,
> 
> Thank you for your feedback! Please try the latest version of our AWQ library, it should be a lot faster now.

Thank you, I will try the latest AWQ. 

I also noticed that if I start TinyChat once, we initialize the weights once, then if I CTRL+C and start TinyChat again, it is not re-initializing the weights and goes straight to the chat. Not sure if it's possible to skip initialization entirely by saving initialized weights?

**Comment by casperbh96** [comment]
Thank you for this update. My model is now initialized in 0.8s. In total, loading is now taking roughly 4 seconds.
