### ISSUE TITLE
TypeError: _request() got an unexpected keyword argument 'https'

### ISSUE THREAD

**Issue by Hukongtao** [mit-han-lab/llm-awq#50]
bash scripts/opt_example.sh
![image](https://github.com/mit-han-lab/llm-awq/assets/16505966/e1e43f9b-97b4-4128-b6ee-030d272d4652)

**Comment by Hukongtao** [comment]
@tonylins Do you know why this problem occurs? Dataset download failed

**Comment by tonylins** [comment]
Hi, I tried running the code and there is no issue. Can you confirm the connection is not blocked by any firewall?
