### ISSUE TITLE
Why scales need to be transformed by sqrt(scales.max() * scales.min())?

### ISSUE THREAD

**Issue by rainyBJ** [mit-han-lab/llm-awq#58]
Great work! 
I have a question about the scales in the repo. Can you explain why we need this: scales = scales / (scales.max() * scales.min()).sqrt() in the implementation, which I didn't find any explanations in the original paper.
<img width="558" alt="image" src="https://github.com/mit-han-lab/llm-awq/assets/49946568/2c592636-7e50-4a69-8255-c463be8952e8">

**Comment by MarsJacobs** [comment]
Thank you for the further clarification! I have one question. In the AWQ implementation, is there a particular reason for using the abs().mean() of weight and activation to explore the scale value? (For comparison, I understand that SmoothQuant utilizes the max value of weight and activation.)

Additional explanations would be greatly helpful in gaining a deeper understanding of AWQ. Thanks in advance!

**Comment by tonylins** [comment]
Hi @MarsJacobs , the most important factor being the accuracy is higher. Our intuition is different compared to SmoothQuant: SmoothQuant wants to preserve the activation outliers for W8A8 quantization; we only want to introduce activation-awareness to the weights. Therefore, we want to use the average to reflect the overall effect from different tokens.

**Comment by MarsJacobs** [comment]
Thank you for your response. Considering the motivational difference between SmoothQuant's shifting activation outliers and AWQ's activation-aware weight scaling, the reasoning behind the abs().mean() implementation becomes much clearer. Thank you for sharing your great work and for providing further answers!
