### ISSUE TITLE
where can i find? vicuna-7b-awq-w4g128.pt?

### ISSUE THREAD

**Issue by andysingal** [mit-han-lab/llm-awq#66]
Hi,
   Where can i find the file: vicuna-7b-awq-w4g128.pt.
Looking forward to hearing from you.
Thanks,
Andy

**Comment by tonylins** [comment]
Hi, please get the model zoo here: https://github.com/mit-han-lab/llm-awq#awq-model-zoo

Basically you get download the pre-computed scales using
```
# git lfs install  # install git lfs if not already
git clone https://huggingface.co/datasets/mit-han-lab/awq-model-zoo awq_cache
```
