### ISSUE TITLE
Calibration dataset sample (in `utils/calib_data.py`) is 404

### ISSUE THREAD

**Issue by michael4tasman** [mit-han-lab/llm-awq#74]
This URL is now 404: `https://the-eye.eu/public/AI/pile/val.jsonl.zst`

https://github.com/mit-han-lab/llm-awq/blob/efea69e16f862df2c14dece260806e7ea23a9fd4/awq/utils/calib_data.py#L7

Is there a suitable replacement, e.g., from Hugging Face?

**Comment by casperbh96** [comment]
> This URL is now 404: `https://the-eye.eu/public/AI/pile/val.jsonl.zst`
> 
> https://github.com/mit-han-lab/llm-awq/blob/efea69e16f862df2c14dece260806e7ea23a9fd4/awq/utils/calib_data.py#L7
> 
> Is there a suitable replacement, e.g., from Hugging Face?

Yeah, I had this too. I am in the process of refactoring AWQ to make it easier to work with. Below is one solution that is likely to yield close to the same results as one would get The Pile dataset. There was a 0.03 difference in perplexity when I tested.

```python
from datasets.builder import DatasetGenerationError

try:
    dataset = load_dataset("json", data_files="https://the-eye.eu/public/AI/pile/val.jsonl.zst", split="train")
except DatasetGenerationError:
    print('The Pile URL is down, using wikitext-103-raw-v1 instead')
    dataset = load_dataset('wikitext', "wikitext-103-raw-v1", split="train")
```

**Comment by tonylins** [comment]
Thanks for the pointer. We will verify if a replaced source can lead to similar results, and will update the link if it works out.

**Comment by tonylins** [comment]
#77 
Feel free to reopen if you have more questions.
