### ISSUE TITLE
Ability to not quantize all weights: is this feature available?

### ISSUE THREAD

**Issue by ri938** [mit-han-lab/llm-awq#76]
In the paper that you leave some weights uncompressed to trade off quality and compression rate.

Am I correct this feature is not currently available in this repo? I would like to tune it to improve the performance of the models I am quantizing.

**Comment by ri938** [comment]
2.2 Protecting Salient Weights by Activation-aware Scaling

**Comment by tonylins** [comment]
Hi, in the paper we quantize all the weights in transformer blocks (i.e., embedding and the final lm_head are not quantized). We do not use the mixed-precision format (which is just for the intuition part). But you can feel free to skip a couple of layers to improve the accuracy.

**Comment by ri938** [comment]
So by default you are quantizing all the weights and not preserving any salient weights?

I noticed there is a documented limitation which I think covers this from the paper:

Limitations: Despite keeping 0.1% of weights in FP16 can improve the quantized performance
without a noticeable increase in model size (measured in total bits), such a mixed-precision data type
will make the system implementation difficult
