### ISSUE TITLE
Output is abnormal when using my own data set (Japanese Instruction) for calibration data

### ISSUE THREAD

**Issue by webbigdata-jp** [mit-han-lab/llm-awq#87]
I am trying to change calib_data.py, but as the title suggests, when I use a Japanese dataset, the output is abnormal.

example
[INST] <<SYS>>
System prompt in Japanese.
<</SYS>>

Instruction prompt in Japanese.
 [/INST] 

An example is shown below, but the output is neither Japanese nor English and is unreadable.

onnées begonnées beginningsROR packaginglan昌 Pin prob Gonchorpon Jahanimal pelottenhamm

The original model works fine with llama2 instructions + fine-tuning in Japanese.
It would be helpful if you could tell me if you have any hints.
Thanks.

**Comment by webbigdata-jp** [comment]
maybe It's my misstake.

**Comment by gameveloster** [comment]
@webbigdata-jp How did you fix it?

And how do you decide what to include in your calibration data?
