### ISSUE TITLE
Compilation issue when following "Efficient Kernels Step" in install process

### ISSUE THREAD

**Issue by knnair** [mit-han-lab/llm-awq#89]
When I try to install efficient kernel step using
cd awq/kernels
python setup.py install

There are errors related to ptxas. I am using the following conda install steps
conda create -n awq python=3.10 -y
conda install -c "nvidia/label/cuda-11.7.1" cuda-toolkit

I was forced to install cuda-toolkit 11.7 by the following error when I try to use the latest cuda version
"The detected CUDA version (12.2) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions"

Compile Command: 
"/wrk/hdstaff/kna/miniconda3/envs/awq/bin/nvcc -I/wrk/hdstaff/kna/miniconda3/envs/awq/lib/python3.10/site-packages/torch/include -I/wrk/hdstaff/kna/miniconda3/envs/awq/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/wrk/hdstaff/kna/miniconda3/envs/awq/lib/python3.10/site-packages/torch/include/TH -I/wrk/hdstaff/kna/miniconda3/envs/awq/lib/python3.10/site-packages/torch/include/THC -I/wrk/hdstaff/kna/miniconda3/envs/awq/include -I/wrk/hdstaff/kna/miniconda3/envs/awq/include/python3.10 -c csrc/quantization/gemm_cuda_gen.cu -o build/temp.linux-x86_64-cpython-310/csrc/quantization/gemm_cuda_gen.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -std=c++17 -DENABLE_BF16 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --threads=8 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=awq_inference_engine -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70
"

Error log: 
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 892; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 892; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 900; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 900; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 908; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 908; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 916; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 916; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 924; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 924; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 928; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 932; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 936; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 940; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 944; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 948; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 952; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 956; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 964; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 964; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 972; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 972; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 980; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 980; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 988; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 988; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 996; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 996; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1000; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1004; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1008; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1012; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1016; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1020; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1024; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1028; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1834; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1834; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1842; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1842; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1850; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1850; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1854; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1858; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1862; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1866; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1874; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1874; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1882; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1882; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1890; error   : Feature 'ldmatrix' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1890; error   : Modifier '.m8n8' requires .target sm_75 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1894; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1898; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1902; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas /tmp/tmpxft_00001f6c_00000000-6_gemm_cuda_gen.ptx, line 1906; error   : Feature '.m16n8k16' requires .target sm_80 or higher
ptxas fatal   : Ptx assembly aborted due to errors

**Comment by Alvant** [comment]
@knnair I am not sure about this error myself, but it [might depend on the CUDA cards](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/#volta-cuda-9-and-later). For example, I got the same error on the server with V100. However, the installation was successful on the server with A100.

**Comment by knnair** [comment]
Thanks a ton. I am running on a V100 . I will run this on A100
