### ISSUE TITLE
4-bit pack order

### ISSUE THREAD

**Issue by flytigerw** [mit-han-lab/llm-awq#91]
Why is the 4-bit data  packed in the following order? : 
<img width="384" alt="image" src="https://github.com/mit-han-lab/llm-awq/assets/48581026/41a41864-4b4e-441e-9413-4fcadef4bb27">
Why not pack it in a sequential order ?

**Comment by K024** [comment]
https://github.com/mit-han-lab/llm-awq/blob/be78265bc08aeb2df53a0ae49dba0fe88756da4b/awq/quantize/qmodule.py#L93-L94

Any detailed commit information about the changes?
