### ISSUE TITLE
Will Open-Flamingo be added into AWQ Model Zoo?

### ISSUE THREAD

**Issue by Starmys** [mit-han-lab/llm-awq#98]
As the AWQ paper showed results on Open-Flamingo, will you upload pre-computed AWQ search results for Open-Flamingo?

**Comment by tonylins** [comment]
Hi @Starmys , OpenFlamingo used a frozen LLM backbone (e.g., LLaMA). We simply drop-in replace the LLM backbone with the quantized variant.
